CREATE ROLE nail_profit_app
  WITH LOGIN PASSWORD 'nail_profit_app'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;

GRANT CONNECT ON DATABASE nail_profit TO nail_profit_app;
GRANT USAGE ON SCHEMA public TO nail_profit_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO nail_profit_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO nail_profit_app;

ALTER DEFAULT PRIVILEGES FOR ROLE nail_profit IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO nail_profit_app;

ALTER DEFAULT PRIVILEGES FOR ROLE nail_profit IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO nail_profit_app;
